image: node:22.13.0
pipelines:
  clone:
    depth: full
  branches:
    main:
      - step:
          name: secret-scan
          script:
            - pipe: atlassian/git-secrets-scan:3.1.0
              variables:
                DEBUG: "true"
      - step:
          name: sonar
          script:
            - pipe: sonarsource/sonarcloud-scan:4.0.0
            - pipe: sonarsource/sonarcloud-quality-gate:0.1.6
      - step:
          name: deploy
          script:
            - |
              env | awk -F= '{print "NUXT_PUBLIC_" $1 "=" $2}' > .env
              export NODE_ENV=production
              npm i -g netlify-cli@19.0.0
              npm ci
              netlify deploy --build --context production --prod --dir=.output/public
options:
  docker: true
