image: node:22.13.0
pipelines:
  branches:
    main:
      - step:
          name: deploy
          script:
            - |
              export NODE_ENV=production
              env | grep MY_SECRET_API_KEY > .env
              npm i -g netlify-cli@19.0.0
              npm ci
              netlify build
              netlify deploy --prod
options:
  docker: true
