image: node:22.13.0
pipelines:
  branches:
    main:
      - step:
          name: deploy
          script:
            - |
              export MY_SECRET_API_KEY=$MY_SECRET_API_KEY
              export NODE_ENV=production
              npm i -g netlify-cli@19.0.0
              npm ci
              netlify deploy --build --context production --prod --dir=.output/public
options:
  docker: true
