image: node:22.13.0
pipelines:
  clone:
    depth: full 
  branches:
    main:
      - step:
          name: secret-scan
          script:
            - pipe: atlassian/git-secrets-scan:3.1.0
      - step:
          name: deploy
          script:
            - |
              echo "NUXT_PUBLIC_MY_READ_TOKEN"=$MY_READ_TOKEN" > .env
              echo "NUXT_PUBLIC_MY_SECRET_API_KEY"=$MY_SECRET_API_KEY" >> .env
              export NODE_ENV=production
              npm i -g netlify-cli@19.0.0
              npm ci
              netlify deploy --build --context production --prod --dir=.output/public
options:
  docker: true
