image: node:22.13.0
pipelines:
  clone:
    depth: full 
  branches:
    main:
      - step:
          name: secret-scan
          script:
            - pipe: atlassian/git-secrets-scan:3.1.0
      - step:
          name: deploy
          script:
            - |
              env | grep -v "NETLIFY_AUTH_TOKEN\|NETLIFY_SITE_ID\|SONAR_TOKEN\|AWS_ACCESS_KEY_ID\|AWS_SECRET_ACCESS_KEY\|AWS_SESSION_TOKEN" | awk -F= '{print "NUXT_PUBLIC_" $1 "=" $2}' > .env
              export NODE_ENV=production
              npm i -g netlify-cli@19.0.0
              npm ci
              netlify deploy --build --context production --prod --dir=.output/public
options:
  docker: true
