image: node:22.13.0
pipelines:
  clone:
    depth: full 
  branches:
    main:
      - step:
          name: security-scan
          script:
            - pipe: karibu-cl/titvo-security-scan-pipe:16
              variables:
                TITVO_API_KEY: $TITVO_API_KEY
                NO_FAIL: "true"
      - step:
          name: deploy
          script:
            - |
              echo "NUXT_PUBLIC_MY_READ_TOKEN=$MY_READ_TOKEN" > .env
              echo "NUXT_PUBLIC_MY_SECRET_API_KEY=$MY_SECRET_API_KEY" >> .env
              export NODE_ENV=production
              npm i -g netlify-cli@19.0.0
              npm ci
              netlify deploy --build --context production --prod --dir=.output/public
options:
  docker: true
