[build]
  command = "npm run generate"
  publish = "/dist"
  base = "/"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/user"
  to = "/.netlify/functions/hola-mundo-ts"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
