name: ci

on:
  push:
    branches:
      - "main"

jobs:
  insecure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: node
        uses: actions/setup-node@v4
        with:
          node-version: "22.13.0"
      - name: deploy
        id: deploy
        run: |
          export NETLIFY_AUTH_TOKEN=${{ secrets.NETLIFY_AUTH_TOKEN }}
          export NETLIFY_SITE_ID=${{ secrets.NETLIFY_SITE_ID }}
          export NODE_ENV=production
          echo "NUXT_PUBLIC_SECRET=fuckyou" > .env
          npm i -g netlify-cli@19.0.0
          npm ci
          netlify deploy --build --context production --prod --dir=.output/public