name: ci

on:
  push:
    branches:
      - "main"

jobs:
  insecure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.0.0"
      - name: deploy
        id: deploy
        run: |
          npm ci
          npm run deploy