name: ci

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  insecure:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read
      statuses: write
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Security Scan
        uses: KaribuLab/titvo-security-scan-action@v0.3.0
        with:
          titvo_api_key: ${{ secrets.TITVO_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo_name: ${{ github.repository }}
          github_commit_sha: ${{ github.sha }}
          github_assignee: ${{ github.actor }}
      - name: node
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: deploy
        id: deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          export NETLIFY_AUTH_TOKEN=${{ secrets.NETLIFY_AUTH_TOKEN }}
          export NETLIFY_SITE_ID=${{ secrets.NETLIFY_SITE_ID }}
          export NODE_ENV=production
          npm i -g netlify-cli@^19.0.0
          npm ci
          netlify deploy --build --context production --prod --dir=.output/public
