name: ci

on:
  push:
    branches:
      - "main"

jobs:
  insecure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: node
        uses: actions/setup-node@v4
        with:
          node-version: "22.13.0"
      - name: deploy
        id: deploy
        run: |
          export MY_SECRET_API_KEY=${{ secrets.MY_SECRET_API_KEY }}
          echo "NUXT_PUBLIC_MY_SECRET_API_KEY=${MY_SECRET_API_KEY}" > .env
          echo "NUXT_PUBLIC_BASE_URL=https://web-ui-vulnerable-github.netlify.app" >> .env
          export NETLIFY_AUTH_TOKEN=${{ secrets.NETLIFY_AUTH_TOKEN }}
          export NETLIFY_SITE_ID=${{ secrets.NETLIFY_SITE_ID }}
          export NODE_ENV=production
          npm i -g netlify-cli@19.0.0
          cat .env
          npm ci
          netlify deploy --build --context production --prod --dir=.output/public